### ISSUE TITLE
DynamicTrees not converting Biomes O' Plenty Trees into Dynamic Ones

### ISSUE THREAD

**Issue by ghost** [the-realest-stu/DynamicTrees-BOP#81] opened 2022-02-20 15:30 UTC
So, I have an issue. I have Dynamic trees and Biomes O' Plenty + The Dynamic Trees for BOP mods in a modpack. However, when I load up a new world, the dynamic trees will spawn with a (what looks like) 50% rate of success. There are still normal trees, and it takes away from the gameplay. I've linked the complete modpack file in a zip attached. If it isn't too much trouble, I appreciate you taking the time to do this
[RealCraft Rebooted.zip](https://github.com/DynamicTreesTeam/DynamicTrees-BOP/files/8104287/RealCraft.Rebooted.zip)
.

**Comment by supermassimo** [comment] 2023-05-14 15:54
Duplicate of https://github.com/DynamicTreesTeam/DynamicTrees-BOP/issues/54

**Closed as completed by supermassimo** 2023-05-14 15:54 UTC
Labels: bug, 1.12.2
