### ISSUE TITLE
(1.18.2) Bug: DTBOP causes all vanilla biomes to stop generating trees after one world reload

### ISSUE THREAD

**Issue by SpaceTruckinn** [the-realest-stu/DynamicTrees-BOP#93] opened 2023-04-23 08:31 UTC
Game Version -- 1.18.2
Forge -- 40.2.0
BOP -- 1.18.2-16.0.0.109
TerraBlender -- 1.2.0.126
DT -- 1.18.2-0.11.0-B10.1
DTBOP -- 1.18.2-3.0.0-B3

If running DTBOP, creating a new world causes all tree generation to function normally, but after exiting the game and returning to that world, all newly generated chunks in vanilla biomes will have no trees. This seems to happen with all vanilla biomes only. BOP biomes are unaffected. 

Disabling DTBOP and reloading the save causes new chunks in vanilla biomes to resume generating trees.

To reproduce, run above mods/versions on 1.18.2 - create a new single biome world using any vanilla biome. Trees will generate normally. Close game, reopen, load that world again, new chunks will not generate trees. Remove/disable DTBOP and return again to that world, new chunks resume generating trees. This does not cause any crashes or graphical issues, only affects worldgen.

[Full MultiMC console output from world reload to save/quit](https://paste.ee/p/NAtDE)
(Below) Journeymap showing clear region where trees stopped generating in an Old Growth Pine Taiga after the save was reloaded once with DTBOP active
![Imgur](https://i.imgur.com/VoZfaO9.png)

**Comment by supermassimo** [comment] 2023-05-14 15:36
Duplicate of https://github.com/DynamicTreesTeam/DynamicTrees-BOP/issues/94

**Closed as completed by supermassimo** 2023-05-14 15:36 UTC
